Repository brittanyrw/emojiscreen, pull requests merged in 2019-10, with the labels that each got.

#583 Response to Issue #403: Add "Top Gun" Movie to EmojiScreen
  data.js
Labels: WIP

#533 #360 - Added new film: Sister Act
  data.js
Labels: WIP or Requires Updates

#515 Added Pippin musical
  data.js
Labels: WIP or Requires Updates

#328 Added Anchorman to Emojiscreens and fixed a few typos (couldn't help myself!)
  README.md
  data.js
Labels: WIP or Requires Updates

#508 Added The hills have eyes
  data.js
Labels: WIP or Requires Updates

#646 Added Watchmen movie
  data.js
Labels: changes-needed

#660 Adding Cidade de Deus and Mary & Max
  data.js
Labels: changes-needed

#704 Add A Quiet Place
  data.js
Labels: WIP or Requires Updates

#712 add rocky horror emoji
  data.js
Labels: WIP or Requires Updates

#711 added life of pi
  data.js
Labels: WIP or Requires Updates
